on:
  push
jobs:
  ejsAction:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show template file
        run: cat views/home.ejs
      - name: EJS Action
        uses: yogonza524/ejs-action@v1.3
        with:
          fileTemplate: 'views/home.ejs'
          variables: '{"name" : "Pepe"}'
          fileOutput: 'home.html'
      - name: Show output file
        run: cat home.html
      - name: Init new repo in dist folder and commit generated files
        run: |
          git add ./
          git config --local user.email "ckumar073@gmail.com"
          git config --local user.name "greengypsy"
          git commit -m "add generated html files"
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: master
        
